# Generated by Django 3.2.7 on 2021-10-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211024_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='available',
        ),
        migrations.AddField(
            model_name='seat',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
