# Generated by Django 3.2.7 on 2021-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
